os: linux
language: c

.com.github.junaruga.ci-clock-test.jobs-definitions:
  - &test_in_container
    language: minimal
    services: docker
    install: true
    before_script: true
    install:
      - |
        travis_retry docker build --rm -t my-container \
          --build-arg BASE_IMAGE=${BASE_IMAGE} \
          -f Dockerfile-centos \
          .
    script:
      - docker run --rm -t my-container make test

jobs:
  include:
    - name: "amd64 (x86_64) - Ubuntu bionic"
      arch: amd64
      dist: bionic
      compiler: gcc
    - name: "amd64 (x86_64) - Ubuntu xenial"
      arch: amd64
      dist: xenial
      compiler: gcc
    - name: "amd64 (x86_64) - Ubuntu trusty"
      arch: amd64
      dist: trusty
      compiler: gcc
    - name: "CentOS 8.1"
      env:
        - BASE_IMAGE=centos:8.1.1911
      <<: *test_in_container
    - name: "CentOS 7.7"
      env:
        - BASE_IMAGE=centos:7.7.1908
      <<: *test_in_container
    - name: "CentOS 6.10"
      env:
        - BASE_IMAGE=centos:6.10
      <<: *test_in_container
    - name: "CentOS 6.6"
      env:
        - BASE_IMAGE=centos:6.6
      <<: *test_in_container
  allow_failures:
    - name: "amd64 (x86_64) - Ubuntu trusty"
    - name: "CentOS 6.10"
    - name: "CentOS 6.6"
  fast_finish: true
install: true
before_script:
  - uname -a
  - uname -r
  - $CC --version
script:
  - make test
branches:
  except:
    # Enable branches except the working in progress branchs "wip/"
    - /^wip\//
